name: Github Actions demo
on: [ push ]
jobs: 
  Test:
  runs-on: ubuntu-latest
     Steps:
     - uses: action/checkout@v2
     - runs: echo "The job was automatically triggered by a ${{ github.event_name }} event."
     - runs: python main.py



 